[package]
name = "yktotp-jsonapi"
version = "0.1.0"
edition = "2021"

[dependencies]
pcsc = "2.7.0"
pcsc-sys = "1.2.0"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"

[dev-dependencies]
test-case = "2.0.2"
